
services:
  api_prisma_node: # Você pode renomear este serviço se quiser
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: api_alunos_db # Nome do seu banco de dados
      